//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaApp.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyAdv
    {
        public int BuyID { get; set; }
        public int ClientID { get; set; }
        public int Price { get; set; }
        public System.DateTime DateConclusion { get; set; }
        public System.DateTime DateCompletion { get; set; }
        public int ServiceID { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
