//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaApp.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImediaEntities : DbContext
    {
        public ImediaEntities()
            : base("name=ImediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static ImediaEntities _cxt;
        public static ImediaEntities GetContext() { if (_cxt == null) _cxt = new ImediaEntities(); return _cxt; }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AdvestingReport> AdvestingReports { get; set; }
        public virtual DbSet<BuyAdv> BuyAdvs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<FlyersType> FlyersTypes { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<Worksheet> Worksheets { get; set; }
    }
}
