//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaApp.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Partner
    {
        public int PartnerID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }


        public string GetPhoto
        {
            get
            {
                if (Photo == null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\images\" + Photo.Trim();
            }
        }
    }
}
