//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaApp.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int WorkerID { get; set; }
        public int AdvRepID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual AdvestingReport AdvestingReport { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
