//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaApp.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worksheet
    {
        public int WorkSheetID { get; set; }
        public int WorkerID { get; set; }
        public int Flyers { get; set; }
        public string Schedule { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
